# Generated by Django 6.0 on 2026-06-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care_notifications', '0002_outbound_and_inapp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='outboundnotification',
            new_name='care_notifi_resourc_9b251a_idx',
            old_name='booking_not_resourc_b8e6a4_idx',
        ),
    ]
