# Generated by Django 6.0 on 2026-06-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_notifications', '0005_webpushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='inappnotification',
            name='facility_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
